### PR TITLE
decode flags cookie as commas are not allowed

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
eek ok

**Comment by aintgoin2goa** [comment]
It won't make any difference - try this out for yourself

    decodeURIComponent('accessGate:off,performanceAB:off')
    "accessGate:off,performanceAB:off"

    decodeURIComponent('performanceAB:off%2Caa:off%2Cads:off')
    "performanceAB:off,aa:off,ads:off"

**Comment by matthew-andrews** [comment]
ok ok :+1:

**Comment by matthew-andrews** [comment]
nice :)

**Pull request merged**
