### PR TITLE
server side client uses eger fetch

### PR DESCRIPTION
**Pull request by wheresrhys**
@matthew-andrews

### CODE REVIEW

**Comment by wheresrhys** [comment]
sorry for typo - I meant eggier fetch

**Comment by ironsidevsquincy** [comment]
For the polling, any reason why we need to fail after n tries? Understandable for the initial update, but polling can just use the cached data (with logging/monitoring so we now if something's going wrong)

**Comment by matthew-andrews** [comment]
> For the polling, any reason why we need to fail after n tries?

i think you're right.  0 retries for polling makes sense.

**Comment by matthew-andrews** [comment]
just might need to make sure failures during the polling don't cause the app to crash…… suspetc i've seen that happen……

**Comment by ironsidevsquincy** [comment]
yeah, that's more what I meant, why does it need to fail at all

**Comment by matthew-andrews** [comment]
i think if it fails for an unexpected error we should crash & post to sentry…… but timeouts or http errors we can safely ignore

**Pull request merged**
